name = "shadow-warden-installer"
main = "src/index.js"
compatibility_date = "2025-01-01"
workers_dev = false
preview_urls = false

# Route: get.shadowwarden.ai/install
# (configure in Cloudflare dashboard: Workers & Pages → installer → Triggers → Custom Domains)

[[kv_namespaces]]
binding = "INSTALL_STATS"
id = "9a67a5312aed471da1922161af78fe25"
preview_id = "650f939d92d54b26974f7cc019dc5bc0"

[vars]
SCRIPT_VERSION = "2.9"
GITHUB_RAW_URL = "https://raw.githubusercontent.com/zborrman/Shadow-Warden-AI/main/scripts/install.sh"
ALLOWED_PATHS   = "/install,/install.sh"
