"""
warden/feed_server/main.py
───────────────────────────
Shadow Warden AI — Threat Intelligence Feed Server.

The central SaaS registry that aggregates anonymised attack rules
from opted-in Shadow Warden instances and publishes them back to
the fleet as a shared intelligence feed.

Run as a standalone service:
    uvicorn warden.feed_server.main:app --host 0.0.0.0 --port 8003

API
───
  POST /rules              Submit an anonymised rule (requires X-Feed-Key)
  GET  /feed.json          Download the published feed (public or key-gated)
  GET  /stats              Feed statistics (admin only)
  POST /admin/rules/{id}/publish    Manually approve a pending rule
  POST /admin/rules/{id}/reject     Manually reject a pending rule
  POST /admin/subscriptions         Create a new subscriber key
  GET  /health             Health check

Environment variables
─────────────────────
  FEED_DB_PATH           SQLite path (default /warden/data/feed_server.db)
  FEED_ADMIN_KEY         Admin API key for moderation endpoints
  FEED_PUBLIC            true = feed.json is public (default false)
  FEED_DAILY_SUBMIT_CAP  max submissions per source per day (default 50)
  FEED_MIN_VET_SOURCES   min unique sources before auto-publish (default 2)
"""
from __future__ import annotations

import hashlib
import logging
import os
import secrets
from contextlib import asynccontextmanager
from datetime import UTC, datetime

from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.responses import JSONResponse
from fastapi.security import APIKeyHeader
from pydantic import BaseModel, Field

from warden.feed_server.store import FeedStore

log = logging.getLogger("warden.feed_server")

_ADMIN_KEY   = os.getenv("FEED_ADMIN_KEY", "")
_PUBLIC_FEED = os.getenv("FEED_PUBLIC", "false").lower() == "true"
_MIN_VET     = int(os.getenv("FEED_MIN_VET_SOURCES", "2"))

_store: FeedStore | None = None

_KEY_HEADER = APIKeyHeader(name="X-Feed-Key", auto_error=False)


# ── Lifespan ──────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    global _store
    _store = FeedStore()
    log.info("FeedServer: store initialised.")
    yield
    if _store:
        _store.close()


app = FastAPI(
    title="Shadow Warden — Threat Intelligence Feed",
    version="0.5.0",
    description=(
        "Central registry for anonymised AI-attack rules generated by "
        "Shadow Warden instances. Opt-in, privacy-first, crowd-vetted."
    ),
    lifespan=lifespan,
)


# ── Auth helpers ──────────────────────────────────────────────────────────────

def _require_admin(api_key: str | None = Depends(_KEY_HEADER)) -> None:
    if not _ADMIN_KEY:
        return   # admin key not set → admin routes open in dev
    if not api_key or not secrets.compare_digest(api_key, _ADMIN_KEY):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Invalid admin key.")


def _require_subscriber(api_key: str | None = Depends(_KEY_HEADER)) -> dict | None:
    """Return subscription info or None (for public access when FEED_PUBLIC=true)."""
    if _PUBLIC_FEED:
        return None
    if not api_key:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "X-Feed-Key required.")
    assert _store is not None
    sub = _store.verify_key(api_key)
    if not sub:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "Unknown or inactive feed key.")
    return sub


# ── Schemas ───────────────────────────────────────────────────────────────────

class _SubmitRequest(BaseModel):
    rule_type:   str = Field("semantic_example", pattern="^(semantic_example|regex_pattern)$")
    value:       str = Field(..., min_length=10, max_length=2000)
    attack_type: str = Field("jailbreak")
    risk_level:  str = Field("high", pattern="^(high|block|medium)$")
    source_id:   str = Field(..., min_length=8, max_length=64)


class _CreateSubRequest(BaseModel):
    tier:  str = Field("free", pattern="^(free|pro|msp)$")
    label: str = Field("", max_length=100)


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health")
async def health() -> dict:
    assert _store is not None
    return {
        "status":  "ok",
        "service": "warden-feed-server",
        "stats":   _store.stats(),
    }


@app.post("/rules", status_code=status.HTTP_201_CREATED, tags=["feed"])
async def submit_rule(
    body: _SubmitRequest,
    _sub: dict | None = Depends(_require_subscriber),
) -> dict:
    """
    Submit an anonymised attack rule to the feed.

    The rule is held in ``pending`` status until it passes auto-vetting
    (submitted by at least N distinct source_ids) or manual approval.
    """
    assert _store is not None
    try:
        result = _store.submit(
            rule_type   = body.rule_type,
            value       = body.value,
            attack_type = body.attack_type,
            risk_level  = body.risk_level,
            source_id   = body.source_id,
        )
    except ValueError as exc:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc))

    # Trigger auto-vetting after every submission
    _store.auto_vet(min_unique_sources=_MIN_VET)

    return result


@app.get("/feed.json", tags=["feed"])
async def get_feed(
    since: str | None = None,
    limit: int = 500,
    _sub: dict | None = Depends(_require_subscriber),
) -> dict:
    """
    Download the published threat intelligence feed.

    Use ``since`` (ISO-8601 timestamp) for incremental syncs.
    Free tier: max 500 rules. Pro/MSP: unlimited (set limit higher).
    """
    assert _store is not None
    if limit > 5000:
        limit = 5000
    return _store.get_feed(since=since, limit=limit)


@app.get("/stats", tags=["admin"])
async def feed_stats(_: None = Depends(_require_admin)) -> dict:
    assert _store is not None
    return _store.stats()


@app.post("/admin/rules/{rule_id}/publish", tags=["admin"])
async def admin_publish(rule_id: str, _: None = Depends(_require_admin)) -> dict:
    assert _store is not None
    if not _store.publish(rule_id):
        raise HTTPException(404, f"Rule {rule_id!r} not found or already published.")
    return {"rule_id": rule_id, "status": "published"}


@app.post("/admin/rules/{rule_id}/reject", tags=["admin"])
async def admin_reject(
    rule_id: str,
    reason:  str = "",
    _: None  = Depends(_require_admin),
) -> dict:
    assert _store is not None
    if not _store.reject(rule_id, reason):
        raise HTTPException(404, f"Rule {rule_id!r} not found or not in pending state.")
    return {"rule_id": rule_id, "status": "rejected"}


@app.post("/admin/subscriptions", status_code=201, tags=["admin"])
async def create_subscription(
    body: _CreateSubRequest,
    _: None = Depends(_require_admin),
) -> dict:
    """
    Create a new subscriber API key.
    Returns the raw key ONCE — it is not stored in plaintext.
    """
    assert _store is not None
    raw_key  = secrets.token_hex(32)
    key_hash = hashlib.sha256(raw_key.encode()).hexdigest()
    sub_id   = _store.add_subscription(key_hash, body.tier, body.label)
    return {
        "sub_id":  sub_id,
        "api_key": raw_key,   # shown once
        "tier":    body.tier,
        "label":   body.label,
    }


# ── Global error handler ──────────────────────────────────────────────────────

@app.exception_handler(Exception)
async def _unhandled(request: Request, exc: Exception) -> JSONResponse:
    log.exception("FeedServer unhandled error: %s", exc)
    return JSONResponse(status_code=500, content={"detail": "Internal feed server error."})
