"""
warden/compliance/soc2.py
━━━━━━━━━━━━━━━━━━━━━━━━
SOC 2 Evidence Bundle exporter.

Produces a ZIP archive suitable for submission to a SOC 2 Type II auditor.
Every file in the bundle is SHA-256 hashed; the hashes are recorded in
06_audit_manifest.json so the auditor can verify bundle integrity.

Bundle contents
───────────────
  README.txt                  — bundle provenance and instructions
  01_config_snapshot.json     — live security configuration (secrets redacted)
  02_threat_statistics.json   — aggregated threat data from analytics logs
  03_audit_chain_status.json  — cryptographic audit chain verification result
  04_evolved_rules.json       — evolved detection rules (if present)
  05_sessions_summary.json    — agent session summaries (tool names, threats — no content)
  06_audit_manifest.json      — SHA-256 of every file above (bundle integrity)

No prompt content, response content, or personal data values are included.
All entity identifiers are pseudonymised (SHA-256[:16]).
"""
from __future__ import annotations

import hashlib
import io
import json
import os
import zipfile
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path


class SOC2Exporter:
    """
    Export a SOC 2 evidence bundle as an in-memory ZIP.

    Usage::

        exporter = SOC2Exporter(audit_trail=_audit_trail)
        buf = exporter.export_bundle(days=30)
        # buf is a BytesIO — stream it as application/zip
    """

    def __init__(self, audit_trail=None) -> None:
        self._audit = audit_trail   # warden.audit_trail.AuditTrail | None

    def export_bundle(self, days: float = 30) -> io.BytesIO:
        """Return a BytesIO containing the complete ZIP bundle."""
        now  = datetime.now(UTC)
        slug = now.strftime("%Y%m%dT%H%M%SZ")

        files: dict[str, bytes] = {}

        files["README.txt"]                  = self._readme(now, days).encode()
        files["01_config_snapshot.json"]     = self._config_snapshot(now)
        files["02_threat_statistics.json"]   = self._threat_statistics(now, days)
        files["03_audit_chain_status.json"]  = self._audit_chain_status(now)
        files["04_evolved_rules.json"]       = self._evolved_rules()
        files["05_sessions_summary.json"]    = self._sessions_summary()
        files["06_audit_manifest.json"]      = self._audit_manifest(files, now)

        buf = io.BytesIO()
        with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
            for name, data in files.items():
                zf.writestr(f"soc2_evidence_{slug}/{name}", data)
        buf.seek(0)
        return buf

    # ── Individual file builders ───────────────────────────────────────────────

    @staticmethod
    def _readme(now: datetime, days: float) -> str:
        return f"""Shadow Warden AI — SOC 2 Evidence Bundle
==========================================
Generated:      {now.isoformat()}
Period covered: last {days:.0f} days
Generator:      Shadow Warden AI Compliance Module v1.8

Contents
--------
01_config_snapshot.json    Security configuration as of bundle generation time.
                           All secret values are redacted ([REDACTED]).
02_threat_statistics.json  Aggregated threat detection statistics from the analytics log.
                           No prompt or response content is included.
03_audit_chain_status.json Cryptographic audit trail verification result.
                           The audit_trail.db uses SHA-256 hash chaining (SOC 2 CC7.2).
04_evolved_rules.json      ML detection rules generated by the Evolution Engine.
05_sessions_summary.json   Agent session summaries (tool names, threat patterns, timestamps).
                           No tool arguments or response content are included.
06_audit_manifest.json     SHA-256 hash of every file in this bundle.
                           Verify integrity: sha256sum <file> and compare.

GDPR Note
---------
This bundle does NOT contain prompt content, response content, personal data values,
raw IP addresses, or any reversible identifier. All entity keys are SHA-256[:16]
pseudonymised. The bundle is safe to share with auditors without additional redaction.

Security Controls mapped to SOC 2 Trust Service Criteria
---------------------------------------------------------
CC6.1  Logical access controls — API key auth, multi-tenant key store, SHA-256 key hashing
CC6.2  Authentication — X-API-Key header, constant-time comparison
CC6.7  Transmission encryption — TLS 1.2+ (nginx proxy)
CC7.1  Threat detection — ML + rule-based pipeline, obfuscation decoder
CC7.2  Monitoring and alerting — Prometheus metrics, Slack/PagerDuty alerting, Grafana dashboards
CC7.3  Incident response — kill-switch API, ERS shadow ban, session revocation
CC9.2  Risk monitoring — Entity Risk Scoring, behavioural attestation chain
A1.2   Capacity management — per-tenant rate limiting, circuit breaker
PI1.3  Processing integrity — atomic log writes, audit hash chain, GDPR erasure endpoint
"""

    @staticmethod
    def _config_snapshot(now: datetime) -> bytes:
        _secret_keys = {
            "ANTHROPIC_API_KEY", "WARDEN_API_KEY", "SLACK_WEBHOOK_URL",
            "PAGERDUTY_ROUTING_KEY", "ELASTIC_API_KEY", "SPLUNK_HEC_TOKEN",
            "POSTGRES_PASSWORD", "DB_PASSWORD", "SECRET_KEY", "AWS_SECRET_ACCESS_KEY",
            "STRIPE_SECRET_KEY", "SAML_PRIVATE_KEY",
        }
        config = {
            "snapshot_at": now.isoformat(),
            "security_settings": {
                k: ("[REDACTED]" if k in _secret_keys else os.getenv(k, "(not set)"))
                for k in sorted([
                    "ANTHROPIC_API_KEY", "WARDEN_API_KEY", "WARDEN_API_KEYS_PATH",
                    "AGENT_SANDBOX_PATH", "AGENT_SANDBOX_STRICT",
                    "RATE_LIMIT_PER_MINUTE", "TENANT_RATE_LIMIT",
                    "SEMANTIC_THRESHOLD", "ERS_SHADOW_BAN_THRESHOLD",
                    "ERS_MEDIUM_THRESHOLD", "ERS_HIGH_THRESHOLD",
                    "STRICT_MODE", "WARDEN_FAIL_STRATEGY",
                    "GDPR_LOG_RETENTION_DAYS", "AGENT_SESSION_TTL",
                    "SHADOW_BAN_ENABLED", "ERS_ENABLED",
                    "SLACK_WEBHOOK_URL", "PAGERDUTY_ROUTING_KEY",
                    "ELASTIC_API_KEY", "SPLUNK_HEC_TOKEN",
                    "REDIS_URL",
                ])
            },
        }
        return json.dumps(config, indent=2).encode()

    @staticmethod
    def _threat_statistics(now: datetime, days: float) -> bytes:
        from warden.analytics.logger import load_entries  # noqa: PLC0415

        entries = load_entries(days=days)
        total   = len(entries)
        blocked = sum(1 for e in entries if not e.get("allowed", True))

        flag_counts: Counter[str] = Counter()
        secret_counts: Counter[str] = Counter()
        entity_counts: Counter[str] = Counter()
        total_tokens   = 0
        total_cost_usd = 0.0

        for e in entries:
            for f in e.get("flags", []):
                flag_counts[f] += 1
            for s in e.get("secrets_found", []):
                secret_counts[s] += 1
            for et in e.get("entities_detected", []):
                entity_counts[et] += 1
            total_tokens   += e.get("payload_tokens", 0)
            total_cost_usd += e.get("attack_cost_usd", 0.0)

        stats = {
            "generated_at":           now.isoformat(),
            "period_days":            days,
            "totals": {
                "requests_processed":     total,
                "requests_blocked":       blocked,
                "requests_allowed":       total - blocked,
                "block_rate_pct":         round(blocked / total * 100, 2) if total else 0.0,
                "payload_tokens_scanned": total_tokens,
                "attack_cost_usd":        round(total_cost_usd, 6),
            },
            "threat_breakdown": {
                "by_flag":         dict(flag_counts.most_common()),
                "by_secret_type":  dict(secret_counts.most_common()),
                "by_entity_type":  dict(entity_counts.most_common()),
            },
            "gdpr_note": (
                "No prompt content, response content, or personal data values are included. "
                "All entity identifiers are SHA-256[:16] pseudonymised."
            ),
        }
        return json.dumps(stats, indent=2).encode()

    def _audit_chain_status(self, now: datetime) -> bytes:
        result: dict = {
            "generated_at": now.isoformat(),
            "status":       "audit_trail_unavailable",
            "chain_valid":  None,
            "entry_count":  0,
            "note":         "AuditTrail not initialised — set AUDIT_DB_PATH and ensure warden started with lifespan.",
        }
        if self._audit is not None:
            try:
                valid, count = self._audit.verify_chain()
                result = {
                    "generated_at":  now.isoformat(),
                    "status":        "verified" if valid else "CHAIN_BROKEN",
                    "chain_valid":   valid,
                    "entry_count":   count,
                    "db_path":       os.getenv("AUDIT_DB_PATH", "/warden/data/audit.db"),
                    "hash_algorithm": "SHA-256",
                    "note": (
                        "Chain is intact — all entries verified against their predecessor hash."
                        if valid else
                        "ALERT: Chain verification failed — possible tampering detected."
                    ),
                }
            except Exception as exc:
                result["status"] = "verification_error"
                result["error"]  = str(exc)
        return json.dumps(result, indent=2).encode()

    @staticmethod
    def _evolved_rules() -> bytes:
        rules_path = Path(os.getenv("DYNAMIC_RULES_PATH", "/warden/data/dynamic_rules.json"))
        if rules_path.exists():
            try:
                data = json.loads(rules_path.read_text())
                # Strip any content fields that could contain payload snippets
                for rule in data.get("rules", []):
                    rule.pop("content", None)
                    rule.pop("example", None)
                data["_note"] = "Evolved detection rules. Content/example fields stripped for export."
                return json.dumps(data, indent=2).encode()
            except Exception:
                pass
        return json.dumps({"rules": [], "_note": "No evolved rules file found."}, indent=2).encode()

    @staticmethod
    def _sessions_summary() -> bytes:
        sessions_path = Path(
            os.getenv("ANALYTICS_DATA_PATH", "/analytics/data")
        ) / "sessions.json"
        sessions: list[dict] = []
        if sessions_path.exists():
            try:
                for raw in sessions_path.read_text().splitlines():
                    raw = raw.strip()
                    if not raw:
                        continue
                    s = json.loads(raw)
                    # Remove events list to keep size manageable; keep metadata
                    s.pop("events", None)
                    sessions.append(s)
            except Exception:
                pass
        return json.dumps({
            "session_count": len(sessions),
            "sessions":      sessions,
            "_note":         "Tool events list omitted. Use GET /api/agent/session/{id} for full detail.",
        }, indent=2).encode()

    @staticmethod
    def _audit_manifest(files: dict[str, bytes], now: datetime) -> bytes:
        manifest: dict = {
            "generated_at": now.isoformat(),
            "algorithm":    "SHA-256",
            "files": {
                name: hashlib.sha256(data).hexdigest()
                for name, data in files.items()
                if name != "06_audit_manifest.json"
            },
        }
        return json.dumps(manifest, indent=2).encode()
