{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "shadow-warden.fullname" . }}-redis
  labels: {{- include "shadow-warden.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: {{ include "shadow-warden.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels: {{- include "shadow-warden.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels: {{- include "shadow-warden.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: {{ .Values.redis.service.port }}
          resources: {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        {{- if .Values.global.storageClass }}
        storageClassName: {{ .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shadow-warden.fullname" . }}-redis
  labels: {{- include "shadow-warden.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector: {{- include "shadow-warden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: {{ .Values.redis.service.port }}
{{- end }}
