"""
warden/output_sanitizer.py
━━━━━━━━━━━━━━━━━━━━━━━━━
OWASP LLM Top 10 — Output Sanitizer.

Scans AI-generated output *before* it reaches the browser or downstream
system, detecting content that is safe as a prompt but dangerous once
rendered or executed.

OWASP categories covered
─────────────────────────
  LLM02 — Insecure Output Handling
    • XSS: <script>, javascript:, onerror=, CSS expression(), data: URIs
    • HTML injection: <iframe>, <object>, <embed>, <form action=...>
    • Markdown link injection: [text](javascript:...) or [text](data:...)
    • SVG with embedded script

  LLM06 — Sensitive Information Disclosure (prompt leakage)
    • AI accidentally echoes back its system prompt
    • Reveals internal tool names, chain-of-thought, or hidden instructions

  LLM08 — Excessive Agency (command injection in AI-tool output)
    • Shell metacharacters in text that will be passed to os.system / subprocess
    • SQL injection patterns in AI-generated query fragments
    • SSRF-class URLs (internal IPs, metadata services) in AI output
    • Path traversal (../../) in filenames generated by AI

Usage
─────
    from warden.output_sanitizer import OutputSanitizer, SanitizeResult

    sanitizer = OutputSanitizer()
    result = sanitizer.scan(ai_response_text)
    if result.risky:
        # block or strip before rendering
        safe_text = result.sanitized
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import StrEnum

# ── Finding categories ────────────────────────────────────────────────────────

class OutputRisk(StrEnum):
    XSS              = "xss"                 # LLM02
    HTML_INJECTION   = "html_injection"      # LLM02
    MARKDOWN_INJECT  = "markdown_inject"     # LLM02
    PROMPT_LEAKAGE   = "prompt_leakage"      # LLM06
    COMMAND_INJECT   = "command_injection"   # LLM08
    SQL_INJECT       = "sql_injection"       # LLM08
    SSRF             = "ssrf"                # LLM08
    PATH_TRAVERSAL   = "path_traversal"      # LLM08


# OWASP LLM category label for each risk type
OWASP_LABEL: dict[OutputRisk, str] = {
    OutputRisk.XSS:             "LLM02 — Insecure Output Handling",
    OutputRisk.HTML_INJECTION:  "LLM02 — Insecure Output Handling",
    OutputRisk.MARKDOWN_INJECT: "LLM02 — Insecure Output Handling",
    OutputRisk.PROMPT_LEAKAGE:  "LLM06 — Sensitive Information Disclosure",
    OutputRisk.COMMAND_INJECT:  "LLM08 — Excessive Agency",
    OutputRisk.SQL_INJECT:      "LLM08 — Excessive Agency",
    OutputRisk.SSRF:            "LLM08 — Excessive Agency",
    OutputRisk.PATH_TRAVERSAL:  "LLM08 — Excessive Agency",
}


@dataclass
class OutputFinding:
    risk:    OutputRisk
    snippet: str          # The matched substring (truncated to 120 chars)
    owasp:   str          # Human-readable OWASP category label


@dataclass
class SanitizeResult:
    findings:   list[OutputFinding] = field(default_factory=list)
    sanitized:  str = ""              # Output after stripping dangerous patterns

    @property
    def risky(self) -> bool:
        return bool(self.findings)

    @property
    def risk_categories(self) -> list[str]:
        return sorted({f.risk.value for f in self.findings})

    @property
    def owasp_categories(self) -> list[str]:
        return sorted({f.owasp for f in self.findings})


# ── Pattern definitions ───────────────────────────────────────────────────────

# ── LLM02: XSS ───────────────────────────────────────────────────────────────
_XSS_PATTERNS: list[re.Pattern[str]] = [
    # <script...> tags (open or self-closing)
    re.compile(r"<script[\s>]", re.IGNORECASE),
    re.compile(r"</script>", re.IGNORECASE),
    # javascript: URI scheme (inline event or href)
    re.compile(r"javascript\s*:", re.IGNORECASE),
    # data: URI with dangerous MIME types
    re.compile(r"data\s*:\s*(text/html|text/javascript|application/javascript|image/svg)", re.IGNORECASE),
    # Inline event handlers on HTML tags
    re.compile(r"on(?:error|load|click|mouseover|focus|blur|input|change|submit)\s*=", re.IGNORECASE),
    # CSS expression() — IE legacy XSS
    re.compile(r"expression\s*\(", re.IGNORECASE),
    # vbscript: URI
    re.compile(r"vbscript\s*:", re.IGNORECASE),
    # SVG <animate> with href pointing to script
    re.compile(r"<animate\b[^>]*\bhref\s*=\s*[\"']?javascript", re.IGNORECASE),
]

# ── LLM02: HTML injection ─────────────────────────────────────────────────────
_HTML_INJECT_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"<\s*iframe\b", re.IGNORECASE),
    re.compile(r"<\s*object\b", re.IGNORECASE),
    re.compile(r"<\s*embed\b",  re.IGNORECASE),
    re.compile(r"<\s*form\b[^>]*\baction\s*=", re.IGNORECASE),
    re.compile(r"<\s*base\b[^>]*\bhref\s*=", re.IGNORECASE),
    re.compile(r"<\s*svg\b[^>]*>.*?<\s*script", re.IGNORECASE | re.DOTALL),
    re.compile(r"<\s*meta\b[^>]*\bhttp-equiv\s*=", re.IGNORECASE),
    re.compile(r"<\s*link\b[^>]*\brel\s*=\s*[\"']?\s*import", re.IGNORECASE),
]

# ── LLM02: Markdown link injection ───────────────────────────────────────────
_MARKDOWN_INJECT_PATTERNS: list[re.Pattern[str]] = [
    # [label](javascript:...) or [label](data:...)
    re.compile(r"\[[^\]]*\]\s*\(\s*(?:javascript|data|vbscript)\s*:", re.IGNORECASE),
    # Markdown image with javascript: src
    re.compile(r"!\[[^\]]*\]\s*\(\s*(?:javascript|data)\s*:", re.IGNORECASE),
]

# ── LLM06: Prompt leakage ─────────────────────────────────────────────────────
_PROMPT_LEAK_PATTERNS: list[re.Pattern[str]] = [
    # System prompt boundary markers common in many LLM deployments
    re.compile(r"\[SYSTEM\]|\<system\>|<\|system\|>|###\s*System\s*:", re.IGNORECASE),
    # OpenAI / Anthropic conversation format leakage
    re.compile(r"<\|im_start\|>|<\|im_end\|>|<\|endoftext\|>", re.IGNORECASE),
    # Common "you are a..." system prompt preambles echoed verbatim
    re.compile(
        r"(?:you are|your instructions? are|your (?:system |hidden )?prompt is|"
        r"as an AI assistant,? your (?:goal|purpose|directive) is)",
        re.IGNORECASE,
    ),
    # Internal tool / function call names leaking into output
    re.compile(r"<tool_call>|<function_call>|<tool_response>", re.IGNORECASE),
    # CoT scratchpad markers
    re.compile(r"<thinking>|<scratchpad>|<reasoning>", re.IGNORECASE),
    # Explicit instruction echo
    re.compile(
        r"(?:my (?:system |hidden )?(?:instructions?|directives?|rules?) (?:are|say|state|include))",
        re.IGNORECASE,
    ),
]

# ── LLM08: Command injection ──────────────────────────────────────────────────
_CMD_INJECT_PATTERNS: list[re.Pattern[str]] = [
    # Classic shell injection metacharacters in a context that looks like a command/filename
    re.compile(r"(?:;\s*(?:rm|del|cat|wget|curl|bash|sh|powershell|cmd)\b)", re.IGNORECASE),
    # Backtick command substitution
    re.compile(r"`[^`]{2,60}`"),
    # $(...) command substitution
    re.compile(r"\$\([^)]{2,60}\)"),
    # Pipe to shell
    re.compile(r"\|\s*(?:bash|sh|zsh|cmd|powershell)\b", re.IGNORECASE),
    # Redirect with dangerous commands
    re.compile(r">\s*/(?:etc/passwd|etc/shadow|proc/self)", re.IGNORECASE),
]

# ── LLM08: SQL injection ──────────────────────────────────────────────────────
_SQL_INJECT_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"(?:'\s*(?:OR|AND)\s*'?\s*\d+\s*=\s*'?\s*\d+|'\s*(?:OR|AND)\s*'[^']*'\s*=\s*'[^']*'|'\s*--)", re.IGNORECASE),
    re.compile(r"\bUNION\s+(?:ALL\s+)?SELECT\b", re.IGNORECASE),
    re.compile(r"\bDROP\s+TABLE\b", re.IGNORECASE),
    re.compile(r"\bINSERT\s+INTO\b.*\bVALUES\b", re.IGNORECASE),
    re.compile(r"\bEXEC(?:UTE)?\s*\(", re.IGNORECASE),
    re.compile(r"\bxp_cmdshell\b", re.IGNORECASE),
    re.compile(r"1\s*=\s*1\s*(?:--|#)", re.IGNORECASE),
]

# ── LLM08: SSRF ──────────────────────────────────────────────────────────────
_SSRF_PATTERNS: list[re.Pattern[str]] = [
    # Cloud metadata endpoints
    re.compile(r"169\.254\.169\.254", re.IGNORECASE),   # AWS/GCP/Azure metadata
    re.compile(r"metadata\.google\.internal", re.IGNORECASE),
    re.compile(r"fd00:ec2::254", re.IGNORECASE),         # IPv6 AWS metadata
    # Internal address ranges in URLs
    re.compile(r"https?://(?:10\.\d+\.\d+\.\d+|172\.(?:1[6-9]|2\d|3[01])\.\d+\.\d+|192\.168\.\d+\.\d+)", re.IGNORECASE),
    re.compile(r"https?://localhost\b", re.IGNORECASE),
    re.compile(r"https?://127\.\d+\.\d+\.\d+", re.IGNORECASE),
    re.compile(r"file://", re.IGNORECASE),
    re.compile(r"gopher://", re.IGNORECASE),
]

# ── LLM08: Path traversal ────────────────────────────────────────────────────
_PATH_TRAVERSAL_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"(?:\.\.[\\/]){2,}"),
    re.compile(r"%2e%2e%2f|%2e%2e/|\.\.%2f", re.IGNORECASE),
    re.compile(r"/(?:etc/passwd|etc/shadow|windows/system32|proc/self/environ)", re.IGNORECASE),
]

# ── Sanitization substitutions ────────────────────────────────────────────────
# Patterns and their safe replacements for the sanitized output.
_STRIP_RULES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"<script[\s\S]*?</script>", re.IGNORECASE), "[SCRIPT REMOVED]"),
    (re.compile(r"<\s*iframe[\s\S]*?(?:/>|</iframe>)", re.IGNORECASE), "[IFRAME REMOVED]"),
    (re.compile(r"javascript\s*:", re.IGNORECASE), "javascript&#58;"),
    (re.compile(r"on(?:error|load|click|mouseover|focus|blur|input|change|submit)\s*=", re.IGNORECASE), "data-blocked-event="),
    (re.compile(r"expression\s*\(", re.IGNORECASE), "blocked("),
    (re.compile(r"<\s*object[\s\S]*?(?:/>|</object>)", re.IGNORECASE), "[OBJECT REMOVED]"),
]


# ── OutputSanitizer ───────────────────────────────────────────────────────────

class OutputSanitizer:
    """
    Scan AI-generated text for OWASP LLM Top 10 output risks.

    Thread-safe; instantiate once and reuse.
    """

    def scan(self, text: str) -> SanitizeResult:
        """
        Scan *text* for dangerous patterns.

        Returns a :class:`SanitizeResult` with all findings and a sanitized
        copy of the text (dangerous patterns stripped/escaped).
        """
        findings: list[OutputFinding] = []

        def _check(patterns: list[re.Pattern[str]], risk: OutputRisk) -> None:
            for pat in patterns:
                for m in pat.finditer(text):
                    snippet = text[max(0, m.start() - 20): m.end() + 20].strip()[:120]
                    findings.append(OutputFinding(
                        risk    = risk,
                        snippet = snippet,
                        owasp   = OWASP_LABEL[risk],
                    ))
                    break  # one finding per pattern is enough to flag the risk

        _check(_XSS_PATTERNS,            OutputRisk.XSS)
        _check(_HTML_INJECT_PATTERNS,    OutputRisk.HTML_INJECTION)
        _check(_MARKDOWN_INJECT_PATTERNS, OutputRisk.MARKDOWN_INJECT)
        _check(_PROMPT_LEAK_PATTERNS,    OutputRisk.PROMPT_LEAKAGE)
        _check(_CMD_INJECT_PATTERNS,     OutputRisk.COMMAND_INJECT)
        _check(_SQL_INJECT_PATTERNS,     OutputRisk.SQL_INJECT)
        _check(_SSRF_PATTERNS,           OutputRisk.SSRF)
        _check(_PATH_TRAVERSAL_PATTERNS, OutputRisk.PATH_TRAVERSAL)

        sanitized = _strip(text)
        return SanitizeResult(findings=findings, sanitized=sanitized)


def _strip(text: str) -> str:
    """Apply sanitization substitutions to produce a safer output."""
    out = text
    for pat, replacement in _STRIP_RULES:
        out = pat.sub(replacement, out)
    return out


# ── Module-level singleton ────────────────────────────────────────────────────

_sanitizer: OutputSanitizer | None = None


def get_sanitizer() -> OutputSanitizer:
    global _sanitizer
    if _sanitizer is None:
        _sanitizer = OutputSanitizer()
    return _sanitizer
