-- ─────────────────────────────────────────────────────────────────────────────
--  Shadow Warden AI — PostgreSQL Initialisation
--  Runs once on first `docker-compose up` (postgres entrypoint).
--  Creates two schemas:
--    warden_core      — application data (sessions, audit trail)
--    warden_analytics — aggregated metrics for BI / external dashboards
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Schemas ───────────────────────────────────────────────────────────────────

CREATE SCHEMA IF NOT EXISTS warden_core;
CREATE SCHEMA IF NOT EXISTS warden_analytics;

-- ── warden_core ───────────────────────────────────────────────────────────────

-- API keys / service-to-service auth tokens
CREATE TABLE IF NOT EXISTS warden_core.api_keys (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT        NOT NULL,
    key_hash    TEXT        NOT NULL UNIQUE,   -- bcrypt hash — never store plaintext
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMPTZ,
    revoked     BOOLEAN     NOT NULL DEFAULT FALSE
);

-- Audit log for every /filter decision (mirrors NDJSON logs.json for SQL queries)
-- NOTE: content is NEVER stored — only metadata (GDPR).
CREATE TABLE IF NOT EXISTS warden_core.filter_audit (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    request_id   TEXT        NOT NULL,
    ts           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    allowed      BOOLEAN     NOT NULL,
    risk_level   TEXT        NOT NULL,     -- LOW | MEDIUM | HIGH | BLOCK
    flags        TEXT[]      NOT NULL DEFAULT '{}',
    secrets_kind TEXT[]      NOT NULL DEFAULT '{}',   -- type names only, not values
    content_len  INTEGER     NOT NULL,
    elapsed_ms   NUMERIC(10,2),
    strict       BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS filter_audit_ts_idx   ON warden_core.filter_audit (ts DESC);
CREATE INDEX IF NOT EXISTS filter_audit_risk_idx ON warden_core.filter_audit (risk_level);

-- Dynamic rules generated by the Evolution Loop
CREATE TABLE IF NOT EXISTS warden_core.dynamic_rules (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_hash     TEXT        NOT NULL UNIQUE,   -- SHA-256 of original content
    attack_type     TEXT        NOT NULL,
    rule_type       TEXT        NOT NULL,           -- semantic_example | regex_pattern
    rule_value      TEXT        NOT NULL,
    description     TEXT,
    severity        TEXT        NOT NULL,
    times_triggered INTEGER     NOT NULL DEFAULT 0
);

-- ── warden_analytics ─────────────────────────────────────────────────────────

-- Hourly aggregated metrics (pre-computed by analytics service)
CREATE TABLE IF NOT EXISTS warden_analytics.hourly_stats (
    hour          TIMESTAMPTZ NOT NULL,
    total         INTEGER     NOT NULL DEFAULT 0,
    allowed       INTEGER     NOT NULL DEFAULT 0,
    blocked       INTEGER     NOT NULL DEFAULT 0,
    high_severity INTEGER     NOT NULL DEFAULT 0,
    avg_ms        NUMERIC(10,2),
    PRIMARY KEY (hour)
);

-- ── warden_core: Threat Intelligence ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS warden_core.threat_intel_items (
    id                  TEXT        PRIMARY KEY,
    source              TEXT        NOT NULL,
    title               TEXT        NOT NULL,
    url                 TEXT        NOT NULL,
    source_url_hash     TEXT        UNIQUE NOT NULL,
    published_at        TEXT,
    raw_description     TEXT,
    relevance_score     NUMERIC(4,3),
    owasp_category      TEXT,
    attack_pattern      TEXT,
    detection_hint      TEXT,
    countermeasure      TEXT,
    status              TEXT        NOT NULL DEFAULT 'new',
    rules_generated     INTEGER     NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    analyzed_at         TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS warden_core.threat_intel_countermeasures (
    id              BIGSERIAL   PRIMARY KEY,
    threat_item_id  TEXT        NOT NULL REFERENCES warden_core.threat_intel_items(id),
    rule_id         TEXT        NOT NULL,
    rule_type       TEXT        NOT NULL,
    rule_value      TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS threat_intel_status_idx ON warden_core.threat_intel_items(status);
CREATE INDEX IF NOT EXISTS threat_intel_source_idx ON warden_core.threat_intel_items(source);

-- ── warden_core: Rule Ledger ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS warden_core.rule_ledger (
    rule_id         TEXT        PRIMARY KEY,
    source          TEXT        NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    pattern_snippet TEXT,
    rule_type       TEXT,
    status          TEXT        NOT NULL DEFAULT 'active'
);

CREATE INDEX IF NOT EXISTS rule_ledger_source_idx ON warden_core.rule_ledger(source);

-- ── warden_core: Billing ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS warden_core.billing_usage (
    id          BIGSERIAL   PRIMARY KEY,
    tenant_id   TEXT        NOT NULL,
    period      TEXT        NOT NULL,   -- YYYY-MM
    requests    INTEGER     NOT NULL DEFAULT 0,
    tokens_in   BIGINT      NOT NULL DEFAULT 0,
    tokens_out  BIGINT      NOT NULL DEFAULT 0,
    cost_usd    NUMERIC(10,6) NOT NULL DEFAULT 0,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, period)
);

CREATE INDEX IF NOT EXISTS billing_tenant_idx ON warden_core.billing_usage(tenant_id);

-- ── warden_core: Red Team Certification Applications ─────────────────────────

CREATE TABLE IF NOT EXISTS warden_core.cert_applications (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name       TEXT        NOT NULL,
    email           TEXT        NOT NULL UNIQUE,
    company         TEXT,
    role            TEXT        NOT NULL,
    experience      TEXT        NOT NULL,   -- junior | mid | senior | lead
    motivation      TEXT        NOT NULL,
    linkedin_url    TEXT,
    github_url      TEXT,
    cohort          TEXT        NOT NULL DEFAULT 'pilot-2025',
    status          TEXT        NOT NULL DEFAULT 'pending',  -- pending | reviewed | accepted | rejected | waitlist
    score           INTEGER,                -- internal review score 0-100
    reviewer_notes  TEXT,
    applied_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at     TIMESTAMPTZ,
    notified_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS cert_app_email_idx   ON warden_core.cert_applications (email);
CREATE INDEX IF NOT EXISTS cert_app_status_idx  ON warden_core.cert_applications (status);
CREATE INDEX IF NOT EXISTS cert_app_cohort_idx  ON warden_core.cert_applications (cohort);
CREATE INDEX IF NOT EXISTS cert_app_applied_idx ON warden_core.cert_applications (applied_at DESC);

-- ── warden_core: Waitlist (early-access / free module registrations) ─────────

CREATE TABLE IF NOT EXISTS warden_core.waitlist (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    email        TEXT        NOT NULL UNIQUE,
    full_name    TEXT        NOT NULL,
    company      TEXT,
    modules      TEXT[]      NOT NULL DEFAULT '{}',   -- selected free module IDs
    source       TEXT        NOT NULL DEFAULT 'early-access',
    ip_hash      TEXT,                                 -- SHA-256 of IP (GDPR)
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    confirmed_at TIMESTAMPTZ,
    status       TEXT        NOT NULL DEFAULT 'pending'  -- pending | confirmed | invited
);

CREATE INDEX IF NOT EXISTS waitlist_email_idx  ON warden_core.waitlist (email);
CREATE INDEX IF NOT EXISTS waitlist_status_idx ON warden_core.waitlist (status);
CREATE INDEX IF NOT EXISTS waitlist_created_idx ON warden_core.waitlist (created_at DESC);

-- ── TOTP / Google Authenticator (MFA) ───────────────────────────────────────
-- Added to portal_users via ALTER TABLE so existing DBs are patched automatically.
ALTER TABLE IF EXISTS warden_core.portal_users
    ADD COLUMN IF NOT EXISTS totp_secret  TEXT,
    ADD COLUMN IF NOT EXISTS totp_enabled BOOLEAN NOT NULL DEFAULT FALSE;

-- ── Grants ────────────────────────────────────────────────────────────────────
-- The docker-compose POSTGRES_USER gets full access to both schemas.
-- Adjust if you use separate read-only users for analytics.

DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_roles WHERE rolname = current_user) THEN
        EXECUTE format('GRANT ALL ON SCHEMA warden_core TO %I', current_user);
        EXECUTE format('GRANT ALL ON SCHEMA warden_analytics TO %I', current_user);
        EXECUTE format('GRANT ALL ON ALL TABLES IN SCHEMA warden_core TO %I', current_user);
        EXECUTE format('GRANT ALL ON ALL TABLES IN SCHEMA warden_analytics TO %I', current_user);
    END IF;
END$$;
