#!/usr/bin/env python3
"""
scripts/fail_open_inventory.py — Stage 3a security inventory.

Scans warden/ for fail-open sites (comments and identifiers mentioning
fail-open) and writes docs/fail-open-inventory.md: a per-module table of
every location, annotated with whether it belongs to a documented protected
invariant (CLAUDE.md) that must NOT be flipped to fail-closed.

Regenerate after any change to fail-open behaviour:
    python scripts/fail_open_inventory.py
"""
from __future__ import annotations

import ast
import re
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "fail-open-inventory.md"

# Documented protected invariants (CLAUDE.md) — fail-open BY DESIGN.
PROTECTED = {
    "x402": "x402 payment gate fail-open — protected invariant (CLAUDE.md)",
    "marketplace/x402_gate.py": "x402 gate errors must never block callers (rule 13)",
    "staff/tools": "Injection pre-screen fail-open on timeout (Rec-1, STAFF invariants)",
    "brand_agent": "Brand Agent gates fail-open independently (marketplace rule 9)",
    "maestro": "MAESTRO auto-isolation steps fail-open independently (rule 6)",
    "clearing": "ClearingEngine dual-write PostgreSQL leg is fail-open (rule 10)",
    "cache.py": "Redis cache fail-open — availability over caching",
    "kya": "KYA registration fail-open (rule 18)",
}

PAT = re.compile(r"fail[-_ ]open", re.I)
# A fail-open site is "covered" when its handler emits the P0 observability
# primitive (warden.observability) so the bypass is a Prometheus counter + alert.
COVER = re.compile(r"record_failopen\s*\(|failopen_guard\s*\(")
# Coverage window: a record_failopen call within ±COVER_WIN lines of the matched
# "fail-open" line counts. Handles the inline style (log → record → return).
COVER_WIN = 4


def protected_reason(rel: str) -> str:
    for key, reason in PROTECTED.items():
        if key in rel:
            return reason
    return ""


def covered_spans(src: str) -> list[tuple[int, int]]:
    """Return (start_line, end_line) ranges of every function/method whose body
    contains a record_failopen / failopen_guard call. A fail-open marker written
    in a function's *docstring* (far from the handler at the bottom) is then still
    credited — coverage is function-scoped, not just line-adjacent."""
    try:
        tree = ast.parse(src)
    except (SyntaxError, ValueError):
        return []
    spans: list[tuple[int, int]] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        has_counter = any(
            isinstance(c, ast.Call)
            and isinstance(getattr(c, "func", None), ast.Name)
            and c.func.id in ("record_failopen", "failopen_guard")
            for c in ast.walk(node)
        )
        if has_counter:
            end = getattr(node, "end_lineno", node.lineno)
            spans.append((node.lineno, end))
    return spans


def is_covered(lines: list[str], idx: int, spans: list[tuple[int, int]]) -> bool:
    """True if line ``idx`` (0-based) is either within ±COVER_WIN lines of a
    counter call, or inside a function that contains one (docstring markers)."""
    lineno = idx + 1
    if any(lo <= lineno <= hi for lo, hi in spans):
        return True
    lo = max(0, idx - COVER_WIN)
    hi = min(len(lines), idx + COVER_WIN + 1)
    return any(COVER.search(lines[j]) for j in range(lo, hi))


def collect_rows() -> list[tuple[str, int, str, str, bool]]:
    """Scan warden/ and return one row per fail-open site:
    ``(rel_path, line_no, context, protected_reason, covered)``. Pure — no I/O
    side effects — so the ratchet test can call it directly."""
    rows: list[tuple[str, int, str, str, bool]] = []
    for p in sorted((REPO / "warden").rglob("*.py")):
        rel = p.relative_to(REPO).as_posix()
        if "__pycache__" in rel or "/tests/" in rel:
            continue
        try:
            src = p.read_text(encoding="utf-8")
        except Exception:  # noqa: BLE001
            continue
        lines = src.splitlines()
        spans = covered_spans(src)
        for i, line in enumerate(lines, 1):
            if PAT.search(line):
                rows.append((rel, i, line.strip()[:110],
                             protected_reason(rel), is_covered(lines, i - 1, spans)))
    return rows


def counterless_rows(rows: list[tuple[str, int, str, str, bool]]
                     ) -> list[tuple[str, int, str, str, bool]]:
    """Fail-open sites that are neither protected-by-invariant nor covered by a
    record_failopen/failopen_guard counter — the P0.2 review/wiring backlog."""
    return [r for r in rows if not r[3] and not r[4]]


def main() -> int:
    rows = collect_rows()
    protected = [r for r in rows if r[3]]
    covered = [r for r in rows if not r[3] and r[4]]
    review = counterless_rows(rows)

    md = [
        "# Fail-Open Inventory (Stage 3a)",
        "",
        f"Generated by `scripts/fail_open_inventory.py` on {date.today().isoformat()}. "
        "Do not edit by hand — regenerate.",
        "",
        f"**Total fail-open sites:** {len(rows)} · "
        f"**protected by design:** {len(protected)} · "
        f"**covered (record_failopen):** {len(covered)} · "
        f"**counter-less (needs review):** {len(review)}",
        "",
        "A *fail-open* site allows the operation when its guard errors. For an",
        "availability-first gateway many are intentional (documented invariants",
        "below); *covered* sites already emit the P0 `record_failopen` counter so",
        "the bypass is alertable; the review list is the counter-less remainder —",
        "the candidate set for `record_failopen` wiring or a fail-closed flag.",
        "",
        "## Protected by documented invariant (do NOT flip)",
        "",
        "| Location | Line | Context | Invariant |",
        "|---|---|---|---|",
    ]
    for rel, ln, ctx, reason, _cov in protected:
        safe_ctx = ctx.replace("|", "\\|")
        md.append(f"| `{rel}` | {ln} | `{safe_ctx}` | {reason} |")

    md += [
        "",
        "## Counter-less — needs review (fail-closed flag or record_failopen wiring)",
        "",
        "| Location | Line | Context |",
        "|---|---|---|",
    ]
    for rel, ln, ctx, _reason, _cov in review:
        safe_ctx = ctx.replace("|", "\\|")
        md.append(f"| `{rel}` | {ln} | `{safe_ctx}` |")

    md += [
        "",
        "## Review policy",
        "",
        "1. Payment / billing / auth fail-opens must emit a fixed-schema audit",
        "   log line (`payment_bypassed` pattern from v7.4) — verify per site.",
        "2. Filter-pipeline fail-opens (stage skipped on error) must increment a",
        "   Prometheus counter so silent degradation is alertable.",
        "3. Anything not in the protected table needs an explicit decision:",
        "   keep-open (document why), flag-gated fail-closed, or hard fail-closed.",
        "",
    ]
    OUT.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}: {len(rows)} sites "
          f"({len(protected)} protected, {len(covered)} covered, "
          f"{len(review)} counter-less)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
