#!/usr/bin/env python3
"""
scripts/fail_open_inventory.py — Stage 3a security inventory.

Scans warden/ for fail-open sites (comments and identifiers mentioning
fail-open) and writes docs/fail-open-inventory.md: a per-module table of
every location, annotated with whether it belongs to a documented protected
invariant (CLAUDE.md) that must NOT be flipped to fail-closed.

Regenerate after any change to fail-open behaviour:
    python scripts/fail_open_inventory.py
"""
from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "docs" / "fail-open-inventory.md"

# Documented protected invariants (CLAUDE.md) — fail-open BY DESIGN.
PROTECTED = {
    "x402": "x402 payment gate fail-open — protected invariant (CLAUDE.md)",
    "marketplace/x402_gate.py": "x402 gate errors must never block callers (rule 13)",
    "staff/tools": "Injection pre-screen fail-open on timeout (Rec-1, STAFF invariants)",
    "brand_agent": "Brand Agent gates fail-open independently (marketplace rule 9)",
    "maestro": "MAESTRO auto-isolation steps fail-open independently (rule 6)",
    "clearing": "ClearingEngine dual-write PostgreSQL leg is fail-open (rule 10)",
    "cache.py": "Redis cache fail-open — availability over caching",
    "kya": "KYA registration fail-open (rule 18)",
}

PAT = re.compile(r"fail[-_ ]open", re.I)


def protected_reason(rel: str) -> str:
    for key, reason in PROTECTED.items():
        if key in rel:
            return reason
    return ""


def main() -> int:
    rows: list[tuple[str, int, str, str]] = []
    for p in sorted((REPO / "warden").rglob("*.py")):
        rel = p.relative_to(REPO).as_posix()
        if "__pycache__" in rel or "/tests/" in rel:
            continue
        try:
            lines = p.read_text(encoding="utf-8").splitlines()
        except Exception:  # noqa: BLE001
            continue
        for i, line in enumerate(lines, 1):
            if PAT.search(line):
                rows.append((rel, i, line.strip()[:110], protected_reason(rel)))

    protected = [r for r in rows if r[3]]
    review = [r for r in rows if not r[3]]

    md = [
        "# Fail-Open Inventory (Stage 3a)",
        "",
        f"Generated by `scripts/fail_open_inventory.py` on {date.today().isoformat()}. "
        "Do not edit by hand — regenerate.",
        "",
        f"**Total fail-open sites:** {len(rows)} · "
        f"**protected by design:** {len(protected)} · "
        f"**needs review:** {len(review)}",
        "",
        "A *fail-open* site allows the operation when its guard errors. For an",
        "availability-first gateway many are intentional (documented invariants",
        "below); the review list is the candidate set for fail-closed flags or,",
        "at minimum, alert-on-bypass metrics.",
        "",
        "## Protected by documented invariant (do NOT flip)",
        "",
        "| Location | Line | Context | Invariant |",
        "|---|---|---|---|",
    ]
    for rel, ln, ctx, reason in protected:
        safe_ctx = ctx.replace("|", "\\|")
        md.append(f"| `{rel}` | {ln} | `{safe_ctx}` | {reason} |")

    md += [
        "",
        "## Needs review (candidate for fail-closed flag or bypass metric)",
        "",
        "| Location | Line | Context |",
        "|---|---|---|",
    ]
    for rel, ln, ctx, _ in review:
        safe_ctx = ctx.replace("|", "\\|")
        md.append(f"| `{rel}` | {ln} | `{safe_ctx}` |")

    md += [
        "",
        "## Review policy",
        "",
        "1. Payment / billing / auth fail-opens must emit a fixed-schema audit",
        "   log line (`payment_bypassed` pattern from v7.4) — verify per site.",
        "2. Filter-pipeline fail-opens (stage skipped on error) must increment a",
        "   Prometheus counter so silent degradation is alertable.",
        "3. Anything not in the protected table needs an explicit decision:",
        "   keep-open (document why), flag-gated fail-closed, or hard fail-closed.",
        "",
    ]
    OUT.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}: {len(rows)} sites "
          f"({len(protected)} protected, {len(review)} to review)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
