#!/usr/bin/env python3
"""
scripts/setup_turso.py — Turso database provisioning for Shadow Warden AI.

Usage:
  TURSO_API_TOKEN=<token> python scripts/setup_turso.py

Creates 5 Turso databases in the shadow-warden-ai org, generates one auth
token per database, and writes all connection strings to .env.turso.

Databases created:
  warden-billing-audit  → billing audit hash chain
  warden-acp            → ACP shared payment tokens + carts + refunds
  warden-marketplace    → M2M marketplace, listings, negotiations, escrow
  warden-sep            → SEP communities, UECIID, peerings, STIX audit
  warden-staff          → staff agent economics + A2A audit trail

After this script completes:
  1. Copy .env.turso contents into your .env file (or production secrets).
  2. Restart warden — it picks up Turso connections automatically.
  3. Run schema migration: TURSO_INIT=true uvicorn warden.main:app --host 0.0.0.0
     (or set TURSO_AUTO_MIGRATE=true in .env to run on every startup).
"""
from __future__ import annotations

import os
import sys
import time
from pathlib import Path

import httpx

ORG        = "shadow-warden-ai"
API_BASE   = "https://api.turso.tech"
TOKEN      = os.environ.get("TURSO_API_TOKEN", "")
GROUP      = "default"           # group must be created manually in the Turso dashboard first
GROUP_LOC  = "aws-us-east-1"    # Turso migrated from Fly.io codes to AWS region codes
OUTPUT     = Path(".env.turso")

DATABASES = [
    ("warden-billing-audit",  "TURSO_URL_BILLING_AUDIT",  "TURSO_TOKEN_BILLING_AUDIT"),
    ("warden-acp",            "TURSO_URL_ACP",             "TURSO_TOKEN_ACP"),
    ("warden-marketplace",    "TURSO_URL_MARKETPLACE",     "TURSO_TOKEN_MARKETPLACE"),
    ("warden-sep",            "TURSO_URL_SEP",             "TURSO_TOKEN_SEP"),
    ("warden-staff",          "TURSO_URL_STAFF",           "TURSO_TOKEN_STAFF"),
]


def _headers() -> dict:
    return {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}


def _create_database(client: httpx.Client, name: str) -> str:
    """Create a Turso database; return its hostname. Skip if already exists."""
    r = client.post(
        f"{API_BASE}/v1/organizations/{ORG}/databases",
        json={"name": name, "group": GROUP},
        headers=_headers(),
    )
    if r.status_code in (409, 422) and "already exists" in r.text.lower():
        print(f"  !!  {name}: already exists -- fetching hostname")
        r2 = client.get(
            f"{API_BASE}/v1/organizations/{ORG}/databases/{name}",
            headers=_headers(),
        )
        r2.raise_for_status()
        return r2.json()["database"]["Hostname"]
    r.raise_for_status()
    hostname = r.json()["database"]["Hostname"]
    print(f"  OK  created {name} -> {hostname}")
    return hostname


def _create_token(client: httpx.Client, name: str) -> str:
    """Generate a read-write auth token for the named database."""
    r = client.post(
        f"{API_BASE}/v1/organizations/{ORG}/databases/{name}/auth/tokens",
        params={"authorization": "full-access"},
        headers=_headers(),
        timeout=30,
    )
    r.raise_for_status()
    return r.json()["jwt"]


def main() -> None:
    if not TOKEN:
        print("ERROR: TURSO_API_TOKEN is not set.")
        print("  Go to https://app.turso.tech/shadow-warden-ai → Settings → API Tokens")
        print("  Then run: TURSO_API_TOKEN=<token> python scripts/setup_turso.py")
        sys.exit(1)

    print(f"Provisioning {len(DATABASES)} Turso databases in org '{ORG}'...\n")

    env_lines: list[str] = [
        "# Turso connection strings — generated by scripts/setup_turso.py",
        f"# Generated: {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}",
        "",
    ]

    with httpx.Client(timeout=30) as client:
        # Verify token works
        r = client.get(f"{API_BASE}/v1/organizations/{ORG}", headers=_headers())
        if r.status_code == 401:
            print("ERROR: Invalid TURSO_API_TOKEN — got 401 Unauthorized.")
            sys.exit(1)
        r.raise_for_status()
        print(f"Authenticated as org: {r.json().get('name', ORG)}\n")

        results: list[dict] = []
        for db_name, url_var, token_var in DATABASES:
            print(f"Processing {db_name}...")
            hostname = _create_database(client, db_name)
            time.sleep(1)   # brief pause — Turso needs time to provision the DB
            token = _create_token(client, db_name)
            url = f"libsql://{hostname}"
            print(f"  OK  token issued for {db_name}\n")
            results.append({
                "db_name":   db_name,
                "hostname":  hostname,
                "url_var":   url_var,
                "token_var": token_var,
                "url":       url,
                "token":     token,
            })
            env_lines.extend([
                f"# {db_name}",
                f'{url_var}="{url}"',
                f'{token_var}="{token}"',
                "",
            ])

    # Write .env.turso
    OUTPUT.write_text("\n".join(env_lines), encoding="utf-8")
    print(f"Written to {OUTPUT}")
    print("\nNext steps:")
    print("  1. Add .env.turso contents to your .env file (or production secrets)")
    print("  2. docker-compose restart warden")
    print("  3. The warden service auto-migrates schemas on startup (TURSO_AUTO_MIGRATE=true)")
    print("\nDatabase URLs:")
    for r in results:
        print(f"  {r['url_var']} = {r['url']}")


if __name__ == "__main__":
    main()
