{{- if .Values.warden.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shadow-warden.fullname" . }}-warden-data
  labels:
    {{- include "shadow-warden.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.warden.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.warden.persistence.size }}
  {{- if .Values.warden.persistence.storageClass }}
  storageClassName: {{ .Values.warden.persistence.storageClass }}
  {{- end }}
{{- end }}
