apiVersion: v1
kind: Service
metadata:
  name: {{ include "shadow-warden.fullname" . }}-warden
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shadow-warden.labels" . | nindent 4 }}
    app.kubernetes.io/component: warden
spec:
  type: {{ .Values.warden.service.type }}
  ports:
    - port: {{ .Values.warden.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "shadow-warden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: warden
