{{- if .Values.warden.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "shadow-warden.fullname" . }}-warden
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "shadow-warden.fullname" . }}-warden
  minReplicas: {{ .Values.warden.hpa.minReplicas }}
  maxReplicas: {{ .Values.warden.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.warden.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.warden.hpa.targetMemoryUtilizationPercentage }}
{{- end }}
